name: NuGet Publish
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs: {}
jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'
          source-url: https://nuget.pkg.github.com/BezaluLLC/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Install Kiota CLI
        run: dotnet tool install --global Microsoft.OpenApi.Kiota
      - name: Generate SDK
        run: |
          kiota generate \
            --language CSharp \
            --openapi https://app.ninjarmm.com/apidocs/NinjaRMM-API-v2.json \
            --class-name NinjaOneClient \
            --namespace-name NinjaOne.Client \
            --output ./Sdk \
            --clean-output \
            --ll warning
      - run: dotnet build --configuration Release
      - name: Create the package
        run: dotnet pack --configuration Release
      - name: Publish the package to GPR
        run: dotnet nuget push bin/Release/*.nupkg --skip-duplicate
